### ISSUE TITLE
Implement Segment

### ISSUE THREAD

**Issue by rnadomingos** [rnadomingos/backend_storeFlow#1]
I'll implement segment, inserting the necessary use cases:

- Create
- Read
- Update
- Delete

**Comment by raulrocha2** [comment]
Hi Renan, OK! 
I'll install typeorm, tsyring to implement singleton pattern, archives configuration docker and docker-compose to run both app server and postgres data base in containers

**Comment by rnadomingos** [comment]
Hi Raul! I finished implementing Segment and pushed to github.

**Comment by rnadomingos** [comment]
Finished

**Comment by raulrocha2** [comment]
That's great! This projects is going very well until now, I'm implementing authenticate user with token.
