### ISSUE TITLE
Hi Renan, OK!

### ISSUE THREAD

**Issue by raulrocha2** [rnadomingos/backend_storeFlow#2]
"Hi Renan, OK! 
I'll install typeorm, tsyring to implement singleton pattern, archives configuration docker and docker-compose to run both app server and postgres data base in containers"

I finished that above, the latest branch a push here is docker. 

_Originally posted by @raulrocha2 in https://github.com/rnadomingos/backend_storeFlow/issues/1#issuecomment-1095001729_

**Comment by rnadomingos** [comment]
Hi Raul! Great!
I'm already using these feat. Thanks!

**Comment by rnadomingos** [comment]
Closed.
